# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude 39.2546000
datum_longitude: &datum_longitude -89.0287000


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[39.4990000, -88.4897000], [39.4990000, -89.0287000], [39.2546000, -89.0287000], [39.2546000, -88.4897000]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -23221.399123240022
  xmax: 23221.399123240022
  ymin: 13566.971703721423
  ymax: -13566.971703721423

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

