# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude 44.6875000
datum_longitude: &datum_longitude -93.3627000


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[44.7349000, -93.3146000], [44.7349000, -93.3627000], [44.6875000, -93.3627000], [44.6875000, -93.3146000]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -1905.7679537154122
  xmax: 1905.7679537154122
  ymin: 2633.6893749404635
  ymax: -2633.6893749404635

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

