# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude 47.1883000
datum_longitude: &datum_longitude -122.2020000


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[47.2510000, -122.1360000], [47.2510000, -122.2020000], [47.1883000, -122.2020000], [47.1883000, -122.1360000]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -2499.5430672678367
  xmax: 2499.5430672678367
  ymin: 3485.340166823223
  ymax: -3485.340166823223

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

