# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude 33.8392600
datum_longitude: &datum_longitude -118.0025500


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[33.8468700, -117.9933500], [33.8468700, -118.0025500], [33.8392600, -118.0025500], [33.8392600, -117.9933500]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -425.7499296844821
  xmax: 425.7499296844821
  ymin: 422.0489052020444
  ymax: -422.0489052020444

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

