# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude 53.27174735521536
datum_longitude: &datum_longitude -0.5231451576007784


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[53.27174735521536, -0.5231451576007784], [53.27261998021257, -0.5233739127998016], [53.27248320426982, -0.5238426842788257], [53.27159431683553, -0.5251416207272774], [53.27156539386626, -0.5250535366501452], [53.2715189233655, -0.5249864628288881], [53.27146320287914, -0.5249387335427746]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -100
  xmax: 100
  ymin: -100
  ymax: 100

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

