# Define site datum - best to be in the center of the field of interest
datum_latitude: &datum_latitude 51.5227000
datum_longitude: &datum_longitude -0.1684000


# Define GNSS Fence coordinates [lat, lon]
gnss_fence:
  gnss_fence_coords: [[51.5378000, -0.1439000], [51.5378000, -0.1684000], [51.5227000, -0.1684000], [51.5227000, -0.1439000]]

# Define map size (x east, y north) in meters from the datum
gmapping:
  xmin: -850.0830610672994
  xmax: 850.0830610672994
  ymin: 840.0010005220172
  ymax: -840.0010005220172

mapviz_initialize_origin:
  local_xy_origins:
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]

