version: 1.2.4

#STANDARD AGENTS
debug_agents:
  - agent_id: storage_fhu
    setup: storage
    local_properties:
        rviz_default_colour: 'FFFF00'
        initial_location: WayPoint398
  - agent_id: hunter_001
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: 'FF0000' #red
        initial_location: WayPoint361
  - agent_id: hunter_002
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '00FF00' #lime
        initial_location: WayPoint362
  - agent_id: hunter_003
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '0000FF' #blue
        initial_location: WayPoint365
  - agent_id: hunter_004
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: 'FFFF00' #yellow
        initial_location: WayPoint367
  - agent_id: hunter_005
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: 'FF00FF' #fuchsia
        initial_location: WayPoint369
  - agent_id: hunter_006
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '00FFFF' #aqua
        initial_location: WayPoint372
  - agent_id: hunter_007
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: 'FFA500' #orange
        initial_location: WayPoint374
  - agent_id: hunter_008
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '008080' #teal
        initial_location: WayPoint377
  - agent_id: hunter_009
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '800000' #maroon
        initial_location: WayPoint380
  - agent_id: hunter_010
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '808000' #olive
        initial_location: WayPoint382
SKIP:
  - agent_id: hunter_011
    setup: general_robot_debug
    local_properties:
        rviz_default_colour: '00AA00'
        initial_location: WayPoint384

#TOPOLOGY (Node Descriptors)
special_nodes_2:
  - id: WayPoint360
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint363
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint366
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint368
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint370
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint373
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint375
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint378
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint381
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint383
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint385
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node

special_nodes:
  - id: WayPoint350
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint351
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint352
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint353
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint354
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint355
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint356
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node
  - id: WayPoint357
    descriptors:
      - base_tp_node
      - base_dc_node
      - storage_wait_node
      - wait_node


#ROUTING
planning_format:
    planning_type: fragment_planner
    heterogeneous_map: true
    force_replan_delay: 5.0

#MODULES
included_task_packages:
  - name: task_template_base
  - name: task_template_assignment

  - name: task_template_navigation
    properties:
        debug_robot_total_subnodes: 8
        debug_robot_speedup_factor: 1.0
        #debug_robot_speedup_factor:   1.0 #  1:00:00=1h
        #debug_robot_speedup_factor:   2.0 #    30:00=1h
        #debug_robot_speedup_factor:   4.0 #    15:00=1h
        #debug_robot_speedup_factor:   6.0 #    10:00=1h
        #debug_robot_speedup_factor:  10.0 #     6:00=1h
        #debug_robot_speedup_factor:  15.0 #     4:00=1h
        #debug_robot_speedup_factor:  30.0 #     2:00=1h
        #debug_robot_speedup_factor:  60.0 #     1:00=1h

#  - name: task_template_transportation
#    properties:
#        wait_loading: 45
#        wait_unloading: 40
#        wait_method: 'wait_at_base'

#  - name: task_template_data_collection
  - name: task_template_health_monitoring
    properties:
        min_battery_limit: 30.0
        critical_battery_limit: 40.0
        low_battery_limit: 42.0
        max_battery_limit: 54.0






